Repository iiab/calibre-web, pull requests merged in 2023-11, with the labels that each got.

#6 Online media download support
  cps/editbooks.py
  cps/static/js/main.js
  cps/templates/layout.html
  cps/templates/modal_dialogs.html
  cps/uploader.py
Labels: enhancement

#10 Add download task
  cps/editbooks.py
  cps/tasks/download.py
  cps/uploader.py
Labels: enhancement

#16 Remove unsupported formats
  cps/constants.py
  cps/uploader.py
Labels: enhancement

#17 Handle request
  cps/editbooks.py
Labels: enhancement

#18 Improve task
  cps/tasks/download.py
Labels: enhancement

#19 Revert prefix
  cps/uploader.py
Labels: bug

#21 Remove addToBookshelf
  cps/static/js/main.js
  cps/templates/modal_dialogs.html
Labels: enhancement

#23 Fix unresponsive event
  cps/static/js/main.js
Labels: bug

#27 Remove addToBookshelf
  cps/static/js/main.js
Labels: duplicate

#32 Fix modal
  cps/templates/layout.html
Labels: bug

#33 Stabilize dynamic endpoints resolution
  cps/editbooks.py
  cps/static/js/main.js
Labels: bug, enhancement

#36 Improvements on bookshelf automation
  cps/editbooks.py
  cps/shelf.py
  cps/tasks/download.py
Labels: bug, enhancement

#44 Clarify cps/constants.py and scripts/lb-wrapper [& refine URL validation, to accept http:// legacy URLs w/o SSL/TLS]
  cps/constants.py
  cps/static/js/main.js
  scripts/lb-wrapper
Labels: question

#48 Pin max format [Set 720p 30FPS WebM as the maximum to be downloaded to IIAB, for now?]
  scripts/lb-wrapper
Labels: enhancement, question

#50 Create calibre-web-nginx.conf
  scripts/calibre-web-nginx.conf
Labels: enhancement, question

#55 Time to put scripts/omg.yml on a diet!
  scripts/omg.yml
Labels: enhancement
