Repository iiab/calibre-web, pull requests merged in 2023-12, with the labels that each got.

#63 scripts/lb-wrapper: Try yt-dlp with "--format best --format-sort 'tbr~1000'" [testing shows need for URL validation, clearly communicated, for users who accidentally request the impossible after clicking "Download to IIAB" > "Start"]
  scripts/lb-wrapper
Labels: enhancement, question

#62 scripts/lb-wrapper: Try "--format-sort='tbr~1000'" [i.e. target 1000 kbit/s codecs]
  scripts/lb-wrapper
Labels: enhancement, question

#66 Trim whitespace
  cps/static/js/main.js
Labels: bug

#69 Find webp file [thumbnail/cover/poster for MP4; not just WebM ?]
  cps/uploader.py
Labels: bug

#72 Support PNG, WEBP, GIF, JPG covers/thumbnails
  cps/uploader.py
Labels: enhancement

#81 Remove advanced settings from "Download" modal dialog
  cps/static/js/main.js
  cps/templates/modal_dialogs.html
Labels: enhancement

#82 cps/editbooks.py: move instead of copyfile (for #45)
  cps/editbooks.py
Labels: bug
