Repository iiab/calibre-web, pull requests merged in 2024-01, with the labels that each got.

#87 Suggested improvements for scripts/lb-wrapper
  scripts/lb-wrapper
  scripts/lb-wrapper.greedy
Labels: enhancement

#88 Refactor pattern matching [cps/tasks/download.py: parse yt-dlp output for download progress percentage]
  cps/tasks/download.py
Labels: enhancement

#93 3 regex's (STDERR, STDIN, Python) to parse yt-dlp download progress, for live display in "Tasks" view
  cps/tasks/download.py
  scripts/lb-wrapper
Labels: bug

#90 Update tasks messages based on the current status
  cps/editbooks.py
  cps/tasks/download.py
Labels: enhancement

#95 Improve error handling for failed downloads
  cps/tasks/download.py
Labels: enhancement

#102 Revert to upload task
  cps/editbooks.py
  cps/tasks/download.py
Labels: bug, enhancement

#103 Fix shelf regression
  cps/tasks/download.py
Labels: bug

#109 Rename and persist xklb database
  cps/constants.py
  cps/tasks/download.py
  cps/uploader.py
  scripts/lb-wrapper
Labels: enhancement

#110 Refactor lb-wrapper for command separation
  scripts/lb-wrapper
Labels: enhancement

#111 Decouple the metadata fetching with TaskMetadataExtract
  cps/editbooks.py
Labels: enhancement

#112 Create cps/tasks/metadata_extract.py
  cps/tasks/metadata_extract.py
Labels: enhancement

#113 Call download task from TaskMetadataExtract
  cps/tasks/download.py
Labels: enhancement
