Repository iiab/calibre-web, pull requests merged in 2024-08, with the labels that each got.

#236 Set .mp4 as video only
  cps/uploader.py
Labels: bug

#223 Adjust error message for stuck/slow videos [if elapsed_time >= timeout, e.g. due to unavailable fragments &/or xklb media_check]
  cps/tasks/download.py
Labels: documentation, enhancement, question

#240 12 upstream commits, 29 files changes, 2 merge conflicts resolved (cps/editbooks.py cps/uploader.py)
  cps/about.py
  cps/admin.py
  cps/audio.py
  cps/comic.py
  cps/db.py
  cps/editbooks.py
  cps/epub.py
  cps/helper.py
  cps/isoLanguages.py
  cps/jinjia.py
  cps/search.py
  cps/shelf.py
  cps/static/js/edit_books.js
  cps/static/js/get_meta.js
  cps/static/js/main.js
  cps/tasks/thumbnail.py
  cps/templates/author.html
  cps/templates/book_edit.html
  cps/templates/image.html
  cps/templates/index.html
  cps/templates/layout.html
  cps/templates/search.html
  cps/templates/search_form.html
  cps/templates/shelf.html
  cps/uploader.py
  cps/web.py
  optional-requirements.txt
  setup.cfg
  test/Calibre-Web TestSummary_Linux.html
Labels: enhancement

#239 Sync 12 commits (29 files changed) from upstream
  cps/about.py
  cps/admin.py
  cps/audio.py
  cps/comic.py
  cps/db.py
  cps/editbooks.py
  cps/epub.py
  cps/helper.py
  cps/isoLanguages.py
  cps/jinjia.py
  cps/search.py
  cps/shelf.py
  cps/static/js/edit_books.js
  cps/static/js/get_meta.js
  cps/static/js/main.js
  cps/tasks/thumbnail.py
  cps/templates/author.html
  cps/templates/book_edit.html
  cps/templates/image.html
  cps/templates/index.html
  cps/templates/layout.html
  cps/templates/search.html
  cps/templates/search_form.html
  cps/templates/shelf.html
  cps/uploader.py
  cps/web.py
  optional-requirements.txt
  setup.cfg
  test/Calibre-Web TestSummary_Linux.html
Labels: enhancement

#242 cps/editbooks.py: RENAME update_title_sort TO create_functions (IN move_mediafile) FOR PR #240
  cps/editbooks.py
Labels: bug, enhancement
