Repository iiab/calibre-web, pull requests merged in 2024-07, with the labels that each got.

#207 Make image and videos uploads use the same data structure
  cps/uploader.py
Labels: enhancement

#208 Fix video upload failure [e.g. filenames that contain square brackets]
  cps/uploader.py
Labels: bug, enhancement

#210 Fix regression due to ValueError in file uploading mechanism
  cps/editbooks.py
Labels: bug, enhancement

#211 Adjust message for formerly "live" videos
  cps/tasks/download.py
  cps/tasks/metadata_extract.py
Labels: enhancement

#213 Ensure progress is 100% on task success
  cps/tasks/metadata_extract.py
Labels: bug, enhancement

#216 Tighten messaging of formerly live video's duration (as it downloads)
  cps/tasks/download.py
Labels: documentation, enhancement

#221 Import shutil.move to recover from upstream change (janeczku@bc1c097) to cps/editbooks.py
  cps/editbooks.py
Labels: bug, question

#225 Remove the scene detection filter
  cps/uploader.py
Labels: bug

#227 Increase fragment stuck timeout to 60 seconds [was 30s]
  cps/tasks/download.py
Labels: bug, enhancement

#191 Ensure error and live_status columns are created from the start
  cps/tasks/metadata_extract.py
Labels: bug, enhancement

#229 Increase timeout to 120s [fragment_stuck_timeout = 120 # seconds]
  cps/tasks/download.py
Labels: bug, enhancement

#231 Update & tighten up omg.yml (cloud-init rapid install script)
  scripts/omg.yml
Labels: bug, enhancement
