Repository iiab/calibre-web, pull requests merged in 2024-11, with the labels that each got.

#283 Sync from upstream Calibre-Web release 0.6.24 (2 commit, 3 files changed)
  README.md
  cps/constants.py
  test/Calibre-Web TestSummary_Linux.html
Labels: documentation, enhancement

#285 Strengthen video ID match [PROBLEM: videos with square brackets in their title do not download]
  cps/uploader.py
Labels: bug

#287 Sync from upstream (5 commits, 7 files changed)
  cps.py
  cps/about.py
  cps/debug_info.py
  cps/dep_check.py
  cps/jinjia.py
  cps/translations/de/LC_MESSAGES/messages.po
  cps/web.py
Labels: enhancement

#288 Sync from upstream (3 commits, 56 files changed)
  cps/translations/cs/LC_MESSAGES/messages.mo
  cps/translations/cs/LC_MESSAGES/messages.po
  cps/translations/de/LC_MESSAGES/messages.mo
  cps/translations/de/LC_MESSAGES/messages.po
  cps/translations/el/LC_MESSAGES/messages.mo
  cps/translations/el/LC_MESSAGES/messages.po
  cps/translations/es/LC_MESSAGES/messages.mo
  cps/translations/es/LC_MESSAGES/messages.po
  cps/translations/fi/LC_MESSAGES/messages.mo
  cps/translations/fi/LC_MESSAGES/messages.po
  cps/translations/fr/LC_MESSAGES/messages.mo
  cps/translations/fr/LC_MESSAGES/messages.po
  cps/translations/gl/LC_MESSAGES/messages.mo
  cps/translations/gl/LC_MESSAGES/messages.po
  cps/translations/hu/LC_MESSAGES/messages.mo
  cps/translations/hu/LC_MESSAGES/messages.po
  cps/translations/id/LC_MESSAGES/messages.mo
  cps/translations/id/LC_MESSAGES/messages.po
  cps/translations/it/LC_MESSAGES/messages.mo
  cps/translations/it/LC_MESSAGES/messages.po
  cps/translations/ja/LC_MESSAGES/messages.mo
  cps/translations/ja/LC_MESSAGES/messages.po
  cps/translations/km/LC_MESSAGES/messages.mo
  cps/translations/km/LC_MESSAGES/messages.po
  cps/translations/ko/LC_MESSAGES/messages.mo
  cps/translations/ko/LC_MESSAGES/messages.po
  cps/translations/nl/LC_MESSAGES/messages.mo
  cps/translations/nl/LC_MESSAGES/messages.po
  cps/translations/no/LC_MESSAGES/messages.mo
  cps/translations/no/LC_MESSAGES/messages.po
  cps/translations/pl/LC_MESSAGES/messages.mo
  cps/translations/pl/LC_MESSAGES/messages.po
  cps/translations/pt/LC_MESSAGES/messages.mo
  cps/translations/pt/LC_MESSAGES/messages.po
  cps/translations/pt_BR/LC_MESSAGES/messages.mo
  cps/translations/pt_BR/LC_MESSAGES/messages.po
  cps/translations/ru/LC_MESSAGES/messages.mo
  cps/translations/ru/LC_MESSAGES/messages.po
  cps/translations/sk/LC_MESSAGES/messages.mo
  cps/translations/sk/LC_MESSAGES/messages.po
  cps/translations/sl/LC_MESSAGES/messages.mo
  cps/translations/sl/LC_MESSAGES/messages.po
  cps/translations/sv/LC_MESSAGES/messages.mo
  cps/translations/sv/LC_MESSAGES/messages.po
  cps/translations/tr/LC_MESSAGES/messages.mo
  cps/translations/tr/LC_MESSAGES/messages.po
  cps/translations/uk/LC_MESSAGES/messages.mo
  cps/translations/uk/LC_MESSAGES/messages.po
  cps/translations/vi/LC_MESSAGES/messages.mo
  cps/translations/vi/LC_MESSAGES/messages.po
  cps/translations/zh_Hans_CN/LC_MESSAGES/messages.mo
  cps/translations/zh_Hans_CN/LC_MESSAGES/messages.po
  cps/translations/zh_Hant_TW/LC_MESSAGES/messages.mo
  cps/translations/zh_Hant_TW/LC_MESSAGES/messages.po
  messages.pot
  test/Calibre-Web TestSummary_Linux.html
Labels: enhancement
