Repository iiab/calibre-web, pull requests merged in 2024-06, with the labels that each got.

#169 Increase "fragment stuck" timeout to 30s
  cps/tasks/download.py
Labels: bug

#170 Enhance timeout check to avoid false positives during processing
  cps/tasks/download.py
Labels: bug, enhancement

#174 Match playlist pattern
  scripts/lb-wrapper
Labels: enhancement

#173 Simplify playlists identification [for non-YouTube playlists e.g. Vimeo showcases, Bilibili.tv / Bilibili.com anthologies, etc]
  cps/tasks/metadata_extract.py
Labels: enhancement

#172 Make error status messages user-friendly
  cps/tasks/metadata_extract.py
Labels: documentation, enhancement

#175 Read error from xklb-metadata.db [leveraging yt-dlp STDERR]
  cps/tasks/download.py
Labels: bug, enhancement

#177 Set outtmpl externally [to avoid missing thumbnails; NOTE: archival-quality book & video titles are preserved in 2 SQLite db's]
  cps/uploader.py
  scripts/lb-wrapper
Labels: bug, enhancement

#179 Handle restricted/unavailable videos
  cps/tasks/metadata_extract.py
Labels: bug, enhancement

#180 Build list of URLs simpler
  cps/tasks/metadata_extract.py
Labels: enhancement

#184 Clear input field when download modal is shown
  cps/static/js/main.js
Labels: enhancement

#183 Prepend the video description with the source URL
  cps/uploader.py
Labels: enhancement, question

#182 Display shelf title [name & link in "Tasks" view, when downloading a playlist or channel to IIAB]
  cps/tasks/metadata_extract.py
Labels: enhancement

#192 Return the real shelf title
  cps/editbooks.py
  cps/tasks/metadata_extract.py
Labels: enhancement

#194 Adjust message to warn about problematic videos
  cps/tasks/metadata_extract.py
Labels: bug, enhancement

#195 Safer lb-wrapper: Wrap lb parameters (bash vars) in single quotes
  scripts/lb-wrapper
Labels: enhancement

#193 Prevent stuck videos from carrying over to next download session ["unavailable fragments" ?]
  cps/tasks/download.py
Labels: bug, enhancement

#196 Generate cover [a.k.a. thumbnail/poster] for video manually uploaded
  cps/uploader.py
Labels: bug, enhancement

#200 Clear input field right after URL is submitted
  cps/static/js/main.js
Labels: enhancement

#201 Escape quotes to fix SyntaxError for RPI
  cps/tasks/metadata_extract.py
Labels: bug

#199 Add --live flag to support downloading of "live" videos
  scripts/lb-wrapper
Labels: bug, enhancement
